# Example HTTPRoute resource
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: echo-route-1
    namespace: default
spec:
    parentRefs:
        - name: example-gateway
    hostnames:
        - "test1.example.com"
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /
          backendRefs:
              - name: echo-backend
                port: 8080
